name: Android Build and Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.2'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm install

      - name: Add Android platform
        run: npx cordova platform add android

      - name: Build APK
        run: npx cordova build android --debug --no-telemetry

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-github-action@v1
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: platforms/android/app/build/outputs/apk/debug/app-debug.apk
          folderId: 1VE6-L7WQIN5cyyS3GjdQSYfkZLyGiPNA
